#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

# updating other submodules
git submodule update --init --recursive ~/dotfiles/zgen
git submodule update --init --recursive ~/dotfiles/vim/bundle/Vundle.vim


# install vundle
vim +BundleInstall +qall
#configuring the fonts
fc-cache -vf ~/.fonts

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
