#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"
# updating other submodules
# git submodule update --init --recursive ~/dotfiles/zgen
# git submodule update --init --recursive ~/dotfiles/vim/bundle/Vundle.vim

git submodule foreach -q --recursive 'branch="$(git config -f ~/dotfiles/.gitmodules submodule.$name.branch)"; git checkout $branch'

# install vundle
vim +PluginInstall +qall

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

#configuring the fonts
fc-cache -vf ~/.fonts

#~/dotfiles/vim/bundle/YouCompleteMe/install.sh --clang-completer
