#!/bin/bash -xe


if ! command -v dotbot &> /dev/null
then
    pipx install dotbot
fi

CONFIG="install.conf.yaml"
#
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir ~/src
cd "${BASEDIR}"
git clone https://github.com/tarjoilija/zgen.git "${HOME}/src/zgen" || echo "already cloned"
git submodule update --init --recursive ~/dotfiles/vim/bundle/Vundle.vim

git submodule foreach -q --recursive 'branch="$(git config -f ~/dotfiles/.gitmodules submodule.$name.branch)"; git checkout $branch master; git pull'


dotbot -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# install vundle
vim +PluginInstall +qall

#configuring the fonts
# fc-cache -vf ~/.fonts
