"change the leader from backslash
let mapleader=","

"------------------------------------------------------------------[Plugins]----
" managed by the built-in vim.pack; see lua/plugins.lua
" must be set before the plugin loads; mappings are defined further down
let g:tmux_navigator_no_mappings = 1
if has('nvim-0.12')
  lua require('plugins')
  lua require('lsp')
else
  echohl WarningMsg
  echom 'plugins skipped: vim.pack needs nvim 0.12+'
  echohl None
endif

"------------------------------------------------------------------[General]----
" Create the 'vimrc' autocmd group, used below, and immediately clear it in
" case this file is being sourced a second time.
augroup vimrc | execute 'autocmd!' | augroup END

syntax on

if (has("termguicolors"))
  set termguicolors
endif
"monokai-derived colorscheme shipped with nvim (replaces tomasr/molokai)
silent! colorscheme unokai
"run syntax check on entire document
" autocmd BufEnter * :syntax sync fromstart
autocmd BufRead,BufNewFile .env.* set filetype=sh

set shell=/bin/zsh
set lazyredraw
set nowrap

set colorcolumn=90
"disable auto commenting:
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

set backspace=indent,eol,start

" to disable the global markers
" set shada="NONE"
" set tabstop=4
" set softtabstop=4
" set shiftwidth=4
set expandtab
set listchars=tab:→\ ,space:·,trail:▸,nbsp:+
set background=dark
set autoindent
" set smartindent
"generic folding settings
set foldmethod=syntax
set foldcolumn=1
let javaScript_fold=1
set foldnestmax=10      "allowed depth of sub-folds
set nofoldenable        "dont fold by default
set foldlevelstart=99   "needed for some reason to not fold everything
" set foldlevel=1         "this is just what i use

set mouse=r
set number
"set working directory to current file path
set autochdir

"when pasting into vim:
" set pastetoggle=<F10>

"---------------------------------[Search]----
set hlsearch
set incsearch
set smartcase
set ignorecase

set wildmenu

"window split settings
set splitbelow
set splitright

"allow vilual block cursor to go anywhere
set virtualedit=block

"powerline/airline stuffs:
" Always show statusline
set laststatus=2
let g:airline_powerline_fonts = 1
" let g:airline_theme='powerlineish'
let g:airline_theme='murmur'
" let g:airline_theme='molokai'
" let g:airline_theme='luna'
" Enable the list of buffers
" let g:airline#extensions#tabline#enabled = 1
" " Show just the filename
" let g:airline#extensions#tabline#fnamemod = ':t'

" workaround to deal with laggy response
if ! has('gui_running')
    set ttimeoutlen=10
    augroup FastEscape
        autocmd!
        au InsertEnter * set timeoutlen=0
        au InsertLeave * set timeoutlen=1000
    augroup END
endif

"easier window navigation
nnoremap <silent> <Tab> :wincmd w<CR>
nnoremap <silent> <S-Tab> :wincmd W<CR>

" Space to toggle folds.
nnoremap <Space> za
vnoremap <Space> za

"jumping to beginning and end of lines
noremap B ^
noremap E $

" vim quickscope repurposing t to jump to second blue match
" noremap t 2f
" noremap T 2F

"open file looking thing in new tab
"map gf :tabedit <cfile><CR>
"syntax coloring for arduino
au BufRead,BufNewFile *.ino set filetype=cpp
au BufRead,BufNewFile *.vue set filetype=html

" set conceallevel=1

" autocmd filetype type args

au FileType make            setlocal ts=2 sts=2 tw=2 noet
au FileType lua             setlocal ts=2 sts=2 sw=2 noexpandtab
au Filetype html            setlocal ts=2 sts=2 sw=2
au Filetype javascript      setlocal ts=2 sts=2 sw=2
au Filetype javascriptreact setlocal ts=2 sts=2 sw=2 expandtab
au Filetype php             setlocal ts=4 sts=4 sw=4
au Filetype yaml            setlocal ts=2 sts=2 sw=2 expandtab
au Filetype typescript      setlocal ts=2 sts=2 sw=2 expandtab
au Filetype json            setlocal ts=2 sts=2 sw=2 expandtab

au BufNewFile,BufRead Jenkinsfile setf groovy

" let g:SignatureForceRemoveGlobal = 0

" deal with drag issues when in tmux
" set mouse+=a

"nerdTree
nnoremap <C-f> :NERDTree<CR>

"swap the layouts of horozontal and vertical
"noremap <C-w>h :windo wincmd H<CR>
"noremap <C-w>t :windo wincmd K<CR>

"merge tabs into single page
noremap <C-w>m :Tabmerge<CR>

"telescope (ctrlp replacement, worktree-safe)
if has('nvim')
lua << EOF
local telescope = require('telescope')
local actions = require('telescope.actions')
local action_state = require('telescope.actions.state')

local function create_new_file(prompt_bufnr)
  local prompt = action_state.get_current_line()
  actions.close(prompt_bufnr)
  vim.cmd('edit ' .. vim.fn.fnameescape(prompt))
end

local function clear_prompt(prompt_bufnr)
  action_state.get_current_picker(prompt_bufnr):reset_prompt()
end

telescope.setup {
  defaults = {
    mappings = {
      i = {
        ["<C-t>"] = actions.select_tab,
        ["<C-n>"] = actions.move_selection_previous,
        ["<C-f>"] = create_new_file,
        ["<C-g>"] = clear_prompt,
        ["<C-b>"] = actions.cycle_history_prev,
      },
    },
  },
}

local function project_files()
  local ok = pcall(require('telescope.builtin').git_files, { show_untracked = true })
  if not ok then
    require('telescope.builtin').find_files()
  end
end

vim.keymap.set('n', '<C-p>', project_files, { silent = true })
vim.keymap.set('n', '<C-b>', '<cmd>Telescope buffers<CR>', { silent = true })
EOF
endif
"for windowswap plugin:
"should learn keyboard commands though
let g:windowswap_map_keys = 0 "prevent default bindings
nnoremap <silent> <leader>yw :call WindowSwap#MarkWindowSwap()<CR>
nnoremap <silent> <leader>pw :call WindowSwap#DoWindowSwap()<CR>
nnoremap <silent> <leader>ww :call WindowSwap#EasyWindowSwap()<CR>


"enable matchit plugin:
" runtime macros/matchit.vim

"vim-javascript syntax plugin highlighting enable
let g:javascript_enable_domhtmlcss = 1
"map <F5> <Esc>:EnableFastPHPFolds<Cr>
"map <F6> <Esc>:EnablePHPFolds<Cr>
"map <F7> <Esc>:DisablePHPFolds<Cr>
"to prevent annoying behavior of the folding plugin
let g:DisableAutoPHPFolding = 1



" check file change every 4 seconds ('CursorHold') and reload the buffer upon detecting change
set autoread
au CursorHold * checktime

"do better auto complete brace behavior:
let delimitMate_expand_cr = 1
"let delimitMate_jump_expansion = 0
let delimitMate_expand_space = 1
let delimitMate_matchpairs = '(:),{:},[:]'
" look into this:
"https://github.com/chrisbra/vim_dotfiles/blob/master/plugin/CustomFoldText.vim

"vim-go:
" let g:go_autodetect_gopath = 1

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)
" let g:easy_align_ignore_groups = ['string']

"move between splits, crossing over into tmux panes at the edges
"(vim-tmux-navigator, with g:tmux_navigator_no_mappings set above)
nnoremap <silent> <C-h> :TmuxNavigateLeft<CR>
nnoremap <silent> <C-t> :TmuxNavigateDown<CR>
nnoremap <silent> <C-n> :TmuxNavigateUp<CR>
nnoremap <silent> <C-s> :TmuxNavigateRight<CR>
nnoremap <silent> <C-\> :TmuxNavigatePrevious<CR>

"neovim stuff; move between terminal splits
if has('nvim')
    tnoremap <Esc> <C-\><C-n>
    tnoremap <silent> <C-h> <C-\><C-n>:TmuxNavigateLeft<CR>
    tnoremap <silent> <C-t> <C-\><C-n>:TmuxNavigateDown<CR>
    tnoremap <silent> <C-n> <C-\><C-n>:TmuxNavigateUp<CR>
    tnoremap <silent> <C-s> <C-\><C-n>:TmuxNavigateRight<CR>
endif

"moving splits around
nnoremap <C-w>S <C-w>L
nnoremap <C-w>T <C-w>J
nnoremap <C-w>N <C-w>K

com! ToJson %s/\(\w*\):/"\1"/

function! ToggleMouse()
    " check if mouse is enabled
    if &mouse == 'a'
        " disable mouse
        set mouse=
    else
        " enable mouse everywhere
        set mouse=a
    endif
endfunc

com! FormatJSON %!python -m json.tool

" vim-fugitive gdiff direction
set diffopt+=vertical

" suda.vim save as root
let g:suda_smart_edit = 1

" eslint diagnostics come from the builtin LSP client now; see lua/lsp.lua
" fixes are manual only: :EslintFixAll

" let g:rhubarb_gbrowse_host_order = ['bitbucket', 'github']
" let g:rhubarb_gbrowse_protocol_order = ['https', 'git']


"reference:
"tabm <number> moves tab to that location.
"example: tabm 0 moves tab to location 0 (first location)
"
"let @a = ':s/row\['\(\w*\)'\]/row->\1/g'
" :s/row\['\(\w*\)'\]/row->\1/g
"move existing window into new tab:
":tabedit %<CR>

"freedom in visual mode
" :set virtualedit=all
" then use Afoo to instert multiple columns

" color highlighting
" set tgc
"toggle color codes:
" :ColorToggle

" shebang filetype detection for extensionless scripts
autocmd BufRead,BufNewFile * if getline(1) =~ '^#!.*bun' | setfiletype javascript | endif
