
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# work
# exec-once = /opt/netskope/stagent/stAgentApp

exec-once = hyprpm reload -n
exec-once = nm-applet &
# exec-once = blueman-applet &
exec-once = kanshi &
exec-once = systemctl --user start hyprpolkitagent

exec = sleep 2 && kanshictl reload
# exec = sleep 1 && notify-send "kanshi reloaded"
exec-once = uwsm-app -- hyprpaper

# Extra autostart processes
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- blueman-applet
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- swayosd-server

# exec-once = uwsm-app -- swaybg -i ~/.config/omarchy/current/background -m fill
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = uwsm-app -- walker --gapplication-service

# Slow app launch fix -- set systemd vars
# exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
# exec-once = dbus-update-activation-environment --systemd --all
