#!/bin/bash

op=`hyprctl monitors -j | jq -r '
  ["normal", "90", "180", "270", "flipped", "flipped-90", "flipped-180", "flipped-270"] as $transforms |
  .[] |
  [
    "output \"\(.description)\"",
    "mode \(.width)x\(.height)@\(.refreshRate)",
    "position \(.x),\(.y)",
    "scale \(.scale)",
    "transform \($transforms[.transform])"
  ] | join("\t")
' | column -t -s $'\t'`

echo "profile generated {
$op
}"
