#!/bin/bash

if [ -z "$1" ]; then
    echo "No domain specified"
    exit 1
fi

echo $1
ip=$(dig $1 +short)
echo -e "IP:\n$ip"
echo -e "www:\n$(dig www.$1 +short)"

mx=$(dig mx $1 +short)
mailip=$(dig mail.$1 +short)
ns=$(dig ns $1 +short)

echo -e "mx:\n$mx"
echo -e "mail IP:\n$mailip"
echo -e "NS:\n$ns"
